[package]
name = "termusic"
version = "0.2.1"
authors = ["tramhao <haoxinkui@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19"
tui = { version = "0.15", default-features = false, features = ['crossterm'] }
tuirealm = { "version" = "0.4", features = [ "with-components" ] }
# tui-realm-treeview = {path = "../tui-realm-treeview"} 
tui-realm-treeview = "0.2"
thiserror = "^1.0.0"
log = "0.4"
shellexpand = "2.1"
libmpv = "2.0"
humantime = "2.1"
dirs-next = "2.0"
anyhow = "1.0"
mp3-duration = "0.1"
id3 = "0.6"
rand = "0.8"
regex = "1.5"
viuer = "0.5"
image = "0.23"
ytd-rs = "0.1"
textwrap = "0.13"
reqwest = { version = "0.11", features = ["blocking", "cookies", "gzip","json", "socks"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# serde_derive = "1.0"
# serde_urlencoded = "0.7"
openssl = "0.10"
hex = "0.4"
base64 = "0.13"
lazy_static = "1.4"
urlqstring = "0.3"
custom_error = "*"
# isahc = { version = "^1.0.1", features = ["cookies"] }
# num-bigint = "0.4"
# failure = "0.1.6"
# chrono = "0.4"
# async-std = "^1.6.1"

[dev-dependencies]
pretty_assertions = "0.7"


