[package]
name = "termusic"
version = "0.3.9"
authors = ["tramhao <haoxinkui@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Terminal Music Player written in Rust. Can download music from youtube(netease/migu/kugou) and then embed lyrics and album photos into mp3/m4a files. Need GStreamer installed to play the music."
repository = "https://github.com/tramhao/termusic"
homepage = "https://github.com/tramhao/termusic"
keywords = ["terminal", "tui","music","gstreamer","youtube"]
categories = ["command-line-interface","command-line-utilities", "multimedia::audio"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.13"
crossterm = "0.20"
dirs-next = "2.0"
gstreamer = "0.17"
gstreamer-player = "0.17"
gstreamer-pbutils = "0.17"
hex = "0.4"
humantime = "2.1"
id3 = "0.6"
image = "0.23"
lazy_static = "1.4"
# lofty = "0.2"
log = "0.4"
# mp3-duration = "0.1"
metaflac = "0.2"
mp4ameta = "0.11"
openssl = "0.10"
pinyin = "0.8"
rand = "0.8"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "2.1"
textwrap = "0.14"
toml = "0.5"
tuirealm = "0.6" 
tui-realm-stdlib = "0.6"
tui-realm-treeview = "0.3"
ureq = "2.2"
urlqstring = "0.3"
viuer = "0.5"
ytd-rs = "0.1"


[dev-dependencies]
pretty_assertions = "0.7"

[profile.release]
# lto = "fat"
# codegen-units = 1
# panic = "abort"
