[package]
name = "termusic"
version = "0.1.0"
authors = ["tramhao <haoxinkui@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19"
tui = { version = "0.15", default-features = false, features = ['crossterm'] }
tuirealm = { "version" = "0.3.2", features = [ "with-components" ] }
# tui-realm-treeview = "0.1.0"
thiserror = "^1.0.0"
log = "0.4.14"
