[package]
name = "termusic"
version = "0.6.13"
authors = ["tramhao <haoxinkui@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Terminal Music Player written in Rust. Can download music from youtube(netease/migu/kugou) and then embed lyrics and album photos into mp3/m4a/flac/wav/ogg vorbis files."
repository = "https://github.com/tramhao/termusic"
homepage = "https://github.com/tramhao/termusic"
keywords = ["terminal", "tui","music","youtube","mpv"]
categories = ["command-line-interface","command-line-utilities", "multimedia::audio"]
readme = "README.md"

[[bin]]
name = "termusic"
path = "src/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0"
base64 = "0.13"
cpal = "0.13"
dirs = "4.0"
discord-rich-presence = { version="0.2",optional = true}
gstreamer = { version="0.18", optional = true}
gstreamer-player = { version="0.18",optional = true}
gstreamer-pbutils = { version="0.18",optional = true}
hex = "0.4"
id3 = "1"
if_chain = "1"
image = "0.24"
# infer = "0.7"
# infer = { version="0.7", default-features = false }
lazy_static = "1.4"
libaes = "0.6"
libmpv = { version = "2",  optional = true}
lofty = "0.6"
md5 = "0.7"
num-bigint = "0.4"
pinyin = "0.9"
rand = "0.8"
regex = "^1.5.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "2.1"
souvlaki = { version = "0.5", optional = true }
symphonia = { version = "0.5.0",  features = ["aac","mp3","isomp4"]}
toml = "0.5"
tuirealm = { version = "1", features = ["serialize"] }
tui-realm-stdlib = "1"
tui-realm-treeview = "1"
ureq = "2"
viuer = "0.6"
yaml-rust = "^0.4.5"
ytd-rs = { version = "0.1", features = ["yt-dlp"]}
walkdir = "2"
wildmatch = "2.1"

[features]
default = []
# left for debug
# default = ["mpv"]
mpris = ["souvlaki"]
cover = []
gst = ["gstreamer","gstreamer-player","gstreamer-pbutils"]
mpv = ["libmpv"]
discord = ["discord-rich-presence"]

[dev-dependencies]
pretty_assertions = "1"

[profile.release]
# lto = true
# panic = 'abort'
# opt-level = 'z'
# codegen-units = 1
