[package]
name = "termusic"
version = "0.1.0"
authors = ["tramhao <haoxinkui@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19"
tui = { version = "0.15", default-features = false, features = ['crossterm'] }
tuirealm = { "version" = "0.4.1", features = [ "with-components" ] }
# tui-realm-treeview = {path = "../tui-realm-treeview"} 
tui-realm-treeview = "0.2.0"
thiserror = "^1.0.0"
log = "0.4.14"
shellexpand = "2.1"
# rodio = "0.14.0"
libmpv = "2.0.1"

[dev-dependencies]
pretty_assertions = "0.7.2"


