[package]
name = "music_tui_rs"
version = "0.1.0"
authors = ["tramhao <haoxinkui@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19"
tui = { version = "0.15", default-features = false, features = ['crossterm'] }
tuirealm = { "version" = "0.3.1", features = [ "with-components" ] }
