[package]
name = "termusic"
version = "0.3.0"
authors = ["tramhao <haoxinkui@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Terminal Music Player written in Rust. Can download music from youtube(and netease) and then embed lyrics and album photos into mp3/m4a files. Need GStreamer installed to play the music."
repository = "https://github.com/tramhao/termusic"
homepage = "https://github.com/tramhao/termusic"
keywords = ["terminal", "tui","music","cli","youtube"]
categories = ["command-line-interface","command-line-utilities", "multimedia::audio"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.20"
tuirealm = "0.6" 
tui-realm-stdlib = "0.6"
tui-realm-treeview = "0.3"
log = "0.4"
shellexpand = "2.1"
humantime = "2.1"
dirs-next = "2.0"
anyhow = "1.0"
mp3-duration = "0.1"
id3 = "0.6"
rand = "0.8"
regex = "1.5"
viuer = "0.5"
image = "0.23"
ytd-rs = "0.1"
textwrap = "0.14"
reqwest = { version = "0.11", features = ["blocking", "cookies", "gzip","json", "socks"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
openssl = "0.10"
hex = "0.4"
base64 = "0.13"
lazy_static = "1.4"
urlqstring = "0.3"
custom_error = "1.9"
unicode-truncate = "0.2"
configr = "0.8.0"
gstreamer = "0.17"
gstreamer-player = "0.17"
gstreamer-pbutils = "0.17"
mp4ameta = "0.11"

# [dependencies.vlc-rs]
# git = "https://github.com/garkimasera/vlc-rs.git"

[dev-dependencies]
pretty_assertions = "0.7"


