[package]
name = "termusic"
version = "0.6.9"
authors = ["tramhao <haoxinkui@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Terminal Music Player written in Rust. Can download music from youtube(netease/migu/kugou) and then embed lyrics and album photos into mp3/m4a/flac/wav/ogg vorbis files."
repository = "https://github.com/tramhao/termusic"
homepage = "https://github.com/tramhao/termusic"
keywords = ["terminal", "tui","music","youtube","mpv"]
categories = ["command-line-interface","command-line-utilities", "multimedia::audio"]
readme = "README.md"

[[bin]]
name = "termusic"
path = "src/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0"
base64 = "0.13"
dbus = { version="0.9",optional = true}
dbus-crossroads = { version="0.5",optional = true}
dirs-next = "2.0"
gstreamer = { version="0.17", optional = true}
gstreamer-player = { version="0.17",optional = true}
gstreamer-pbutils = { version="0.17",optional = true}
hex = "0.4"
id3 = "0.6"
if_chain = "1"
image = "0.23"
lazy_static = "1.4"
libaes = "0.6"
libmpv = { version = "2",  optional = true}
lofty = "0.3"
md5 = "0.7"
num-bigint = "0.2"
pinyin = "0.8"
rand = "0.8"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "2.1"
toml = "0.5"
tuirealm = { version = "1", features = ["serialize"] }
tui-realm-stdlib = "1"
tui-realm-treeview = "1"
ureq = "2.2"
viuer = "0.5"
yaml-rust = "0.4"
ytd-rs = { version = "0.1", features = ["yt-dlp"]}
walkdir = "2"
wildmatch = "2.1"
cpal = "0.13"
# symphonia = { git = "https://github.com/pdeljanov/Symphonia",  features = ["aac","mp3","isomp4"]}
symphonia = { version = "0.5.0",  features = ["aac","mp3","isomp4"]}

[features]
default = []
# left for debug
# default = ["gst"]
mpris = ["dbus","dbus-crossroads"]
cover = []
# yt-dlp = ["ytd-rs/yt-dlp"]
gst = ["gstreamer","gstreamer-player","gstreamer-pbutils"]
mpv = ["libmpv"]

[dev-dependencies]
pretty_assertions = "0.7"

[profile.release]
